version: "3.9"
services:
  react-app:
    image: node:18
    volumes:
      - ./react_app:/app # Mapowanie bieżącego katalogu na kontener
    working_dir: /app # Ustaw katalog roboczy na /app w kontenerze
    ports:
      - "3000:3000" # Udostępnij port 3000 na hosta
    command: sh -c "npx create-react-app . && npm start" # Tworzenie aplikacji React i jej uruchomienie